version: "3.7"
################################################################################
# SERVICES
################################################################################
services:
    # ------------------------------------------------------------
    #  nginx
    # ------------------------------------------------------------
    nginx:
        image: nginx:alpine
        ports:
            - "5000:5000"
            - "8000:8000"
        volumes:
            - /etc/nginx/conf.d:/etc/nginx/conf.d:rw
            - /etc/nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd:rw
        depends_on:
            - registry
            - jenkins
    # ------------------------------------------------------------
    #  Registry
    # ------------------------------------------------------------
    registry:
        image: registry:2
        volumes:
            - registry:/var/lib/registry
    # ------------------------------------------------------------
    # jenkins
    # ------------------------------------------------------------
    jenkins:
        container_name: jenkins-docker
        build:
            context: ./jenkins
            dockerfile: jenkins.Dockerfile
        restart: unless-stopped
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.soc
# ------------------------------------------------------------
# volumes
# ------------------------------------------------------------
volumes:
    registry:
    jenkins_home:
