version: "3.7"
################################################################################
# SERVICES
################################################################################
services:
    # ------------------------------------------------------------
    #  nginx
    # ------------------------------------------------------------
    nginx:
        image: nginx:alpine
        ports:
            - "5000:5000"
        volumes:
            - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
            - /etc/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd:rw # password
        depends_on:
            - registry
    # ------------------------------------------------------------
    #  Registry
    # ------------------------------------------------------------
    registry:
        image: registry:2
        ports:
            - "5001:5000"
        volumes:
            - registry:/var/lib/registry
# ------------------------------------------------------------
# volumes
# ------------------------------------------------------------
volumes:
    registry:
