---
#https://github.com/laincloud/lain/blob/0fe5f93d06540300c5dafb94d81b3b69d2c8f1da/playbooks/roles/bootstrap-webrouter-start/tasks/main.yaml
- debug:
    msg: "`{{registry.port}}`"
# tasks file for ansible-role-docker-registry

- name: Create directory docker_compose
  file:
    path: /var/local/docker_compose/registry
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /var/local/docker_compose/registry/docker-compose.yml
#volumes
- name: prepare volume dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/auth

- name: copy configs nginx to volumes
  copy:
    src: "{{ item.src }}"
    dest: "{ item.dest }}"
    mode: 0644
  with_items:
    - src: nginx/conf.d/default.conf
      dest: /etc/nginx/conf.d/default.conf
    - src: nginx/auth/htpasswd
      dest: /etc/nginx/auth/htpasswd
#docker_compose
- community.docker.docker_compose:
    project_src: /var/local/docker_compose/registry/
    state: present
