version: "3.7"
################################################################################
# SERVICES
################################################################################
services:
    # ------------------------------------------------------------
    #  nginx
    # ------------------------------------------------------------
    nginx:
        image: nginx:alpine
        ports:
            - "5000:5000"
        volumes:
            -  /etc/nginx/conf.d:/etc/nginx/conf.d
            -  /etc/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd # password
        depends_on:
            - registry
    # ------------------------------------------------------------
    #  Registry
    # ------------------------------------------------------------
    registry:
        image: registry:2
        volumes:
            - registry:/var/lib/registry
# ------------------------------------------------------------
# volumes
# ------------------------------------------------------------
volumes:
    registry:
