---
- name: Check docker version
  shell: docker --version
  register: docker_version
#  docker_version
- name: process docker_version.stdout var
  set_fact:
    docker_version: "{{ docker_version.stdout | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+') }}"

- name: debug docker_version
  debug:
    msg: "docker_version `{{docker_version}}`"
