---
################################################################################
# 👉                        docker_compose                                 👈 #
################################################################################
- name: Create directory docker_compose
  file:
    path: /var/local/docker_compose
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /var/local/docker_compose/docker-compose.yml
################################################################################
# 👉                    jenkins Dockerfile                                 👈 #
################################################################################


################################################################################
# 👉                      nginx  volume                                    👈 #
################################################################################
# volume dirs
- name: prepare volume dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/auth
    
# copy conf.d
- name: copy configs nginx to volumes
  copy:
    src: "nginx/conf.d/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    mode: 0644
  with_items:
      - registry
      #- jenkins
      - default
################################################################################
# 👉                        nginx  .htpasswd                                👈 #
################################################################################
- name: copy configs nginx to volumes
  copy:
    src: nginx/auth/.htpasswd
    dest: /etc/nginx/auth
    mode: 0644
################################################################################
# 👉                    Run      docker_compose                            👈 #
################################################################################
- community.docker.docker_compose:
    project_src: /var/local/docker_compose/
    state: present
