---
- name: Create directory docker_compose
  file:
    path: /var/local/docker_compose/registry
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /var/local/docker_compose/registry/docker-compose.yml
#volumes
- name: prepare volume dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/auth

- name: copy configs nginx to volumes
  copy:
    src: nginx/conf.d/default.conf
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644

- name: copy configs nginx to volumes
  copy:
    src: nginx/auth/htpasswd
    dest: /etc/nginx/auth
    mode: 0644

#docker_compose
- community.docker.docker_compose:
    project_src: /var/local/docker_compose/registry/
    state: present
