---
# Для HTTPS
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
# Добавляем ключ для докера
- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
# Проверяем Отпечаток
- name: Verify fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
# Добавляем репозиторий amd64
- name: Set up the repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker
    update_cache: yes
# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot
# Install Docker docker-ce-cli containerd.io